### ISSUE TITLE
Progress Bar stopped working with Decimal Values

### ISSUE THREAD

**Issue by mltn123** [chapkovski/progressbaracrossrounds#1]
Just a heads up, Progressbar kept displaying as empty even though "progressrel" reported just fine.
 Turns out bootstrap has some sort of issues with using "," instead of "." on decimal values? Not entirely sure.
`progressrel = int(progressrel) `
fixed it for me.

Thanks for all your work :)

**Comment by mltn123** [comment]
On second thought, seems to be a "error" that occurs when switching the otree localization to german.

**Comment by chapkovski** [comment]
I updated the code so it works for new oTree (and is slightly more nicely looking :)
